### ISSUE TITLE
Unwanted scroll on copy (iOS Safari)

### ISSUE THREAD

**Issue by karnevil9** [zenorocha/clipboard.js#347]
### Minimal example

https://jsfiddle.net/vs2wqkgs/4/

1. Zoom down onto Copy button
2. Click Copy button

### Expected behavior

Expect copy to occur (it does, it puts "Hello!" on the pasteboard), but no scroll.

### Actual behavior

Scrolls up and to the left.

Seems related to your issue #250 Chrome (Windows) has weird scroll-jump behaviour?

### Browsers affected

Mobile Safari.

**Comment by karnevil9** [comment]
You can also visit 

http://clipboardjsbug.s3-website-us-west-2.amazonaws.com

To repro the behavior.

**Comment by cezarlz** [comment]
Same here, iOS 10 Safari, iPhone 5C

**Comment by jonashaag** [comment]
I can reproduce this, iPhone 4S with latest iOS. It also doesn't copy the text but only scrolls.

**Comment by jonashaag** [comment]
Just found this is a duplicate of #320

**Comment by jonashaag** [comment]
Here's a jsfiddle with v 1.5.15 and it's still broken https://jsfiddle.net/mkg3x6xk/

**Comment by zenorocha** [comment]
Hey guys, I'm on vacations right now, feel free to send a pull request if you find a solution.

**Comment by mgleahy** [comment]
I have the same problem in 1.5.16 (with the fix for #320 in https://github.com/zenorocha/clipboard.js/commit/fce625f1515fea353072e4253ead96335e681b18)

It seems like the positioning of the fakeElem textarea object to the far right/left is the source of the issue in  problems on my iPad.

I found that I could solve it myself by replacing the line:

```javascript
this.fakeElem.style[ isRTL ? 'right' : 'left' ] = '-9999px';
```

With this:

```javascript
this.fakeElem.style.opacity = '0';
this.fakeElem.style.zIndex = "-1";
this.fakeElem.style.right = "0px";
this.fakeElem.style.height = "1px";
this.fakeElem.style.width = "1px";
this.fakeElem.style.pointerEvents = "none";
```

And it now works on iPad (and everything else I've tried so far).  If I made the width/height 0px, then it didn't work.

I think maybe it would be nice if we could supply an object on the page to be used in place of the fakeElem object, so that we could style it as appropriate depending on the layout of the page, instead of having it added/created every time a copy event is triggered.  Maybe there's already a simple way to do this (where all my clipboard-enabled objects use the data-clipboard-text property)?

**Comment by felipedrumond** [comment]
As far as I know, iOS does not allow Safari to programmatically copy text to its clipboard. It might be a security measure. Therefore, when you run document.execCommand, it does not do anything at all. While trying to solve this issue with iOS Safari, I implemented the function below to certify that it does work, but don't do in iOS Safari.

```
public copy(value) {
        var input = document.createElement("textarea");

        // Place in top-left corner of screen regardless of scroll position.
        input.style.position = 'fixed';
        input.style.top = '0';
        input.style.left = '0';
        input.style.width = '2em';
        input.style.height = '2em';
        input.style.padding = '0';
        input.style.border = 'none';
        input.style.outline = 'none';
        input.style.boxShadow = 'none';
        input.style.background = 'transparent';

        input.value = value;
        document.body.appendChild(input);
        input.select();

        try {
            var successful = document.execCommand('copy');
            return true;
        } catch (err) {
            console.log('Oops, unable to copy');
            return false;
        }
        finally {
            document.body.removeChild(input);
        }
    }
```

**Comment by mgleahy** [comment]
The changes I made noted above are working for me in the latest iOS in my iPad (using both safari and chrome browser apps).  Other than the undesireable scroll effect, I didn't notice any problems copying text (i.e., the expected text is successfully copied to the clipboard).

**Comment by felipedrumond** [comment]
@mgleahy That's strange. Some iOS devices it works, some don't. In my 6s it does not work in both Safari or Chrome. In my brothers iPhone 6, the same happens.

**Comment by geraldarthur** [comment]
Can confirm this is still an issue with the latest iOS and none of the fake element tweaks mentioned here have worked cc @zenorocha

**Comment by geraldarthur** [comment]
screen capture of the bug on the demo site. this bug matches my [aforementioned](https://github.com/zenorocha/clipboard.js/issues/347#issuecomment-275752739) bug. 

this error can be reproduced when using `data-clipboard-text`, but does not affect elements with `data-clipboard-snippet` attribute @zenorocha 

![iphonese-clipboard-bug2017-01-27](https://cloud.githubusercontent.com/assets/1578563/22389796/50951f1e-e49c-11e6-840c-ee2901223fdf.gif)

**Comment by zenorocha** [comment]
This should be fixed on `v1.6.0`. Let me know if you guys are still having this problem or not.
